export const MarrakechGameABI = [
  // ── Events ──
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint8", name: "playerIndex", type: "uint8" },
      { indexed: false, internalType: "address", name: "wallet", type: "address" },
    ],
    name: "PlayerJoined",
    type: "event",
  },
  { anonymous: false, inputs: [], name: "GameStarted", type: "event" },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint8", name: "playerIndex", type: "uint8" },
      { indexed: false, internalType: "enum MarrakechGame.Direction", name: "direction", type: "uint8" },
    ],
    name: "AssamOriented",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint8", name: "playerIndex", type: "uint8" },
      { indexed: false, internalType: "bytes32", name: "commitHash", type: "bytes32" },
    ],
    name: "DiceCommitted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint8", name: "playerIndex", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "value", type: "uint8" },
    ],
    name: "DiceRevealed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint8", name: "row", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "col", type: "uint8" },
      { indexed: false, internalType: "enum MarrakechGame.Direction", name: "direction", type: "uint8" },
    ],
    name: "AssamMoved",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint8", name: "row", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "col", type: "uint8" },
      { indexed: false, internalType: "enum MarrakechGame.Direction", name: "exitDirection", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "remainingSteps", type: "uint8" },
    ],
    name: "BorderChoiceRequired",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint8", name: "playerIndex", type: "uint8" },
      { indexed: false, internalType: "enum MarrakechGame.Direction", name: "direction", type: "uint8" },
    ],
    name: "BorderDirectionChosen",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint8", name: "fromPlayer", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "toPlayer", type: "uint8" },
      { indexed: false, internalType: "uint16", name: "amount", type: "uint16" },
    ],
    name: "TributeCalculated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "uint8", name: "playerIndex", type: "uint8" }],
    name: "TributeAcknowledged",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint8", name: "playerIndex", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "r1", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "c1", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "r2", type: "uint8" },
      { indexed: false, internalType: "uint8", name: "c2", type: "uint8" },
    ],
    name: "CarpetPlaced",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "uint8", name: "playerIndex", type: "uint8" }],
    name: "PlayerEliminated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "uint8", name: "winnerIndex", type: "uint8" },
      { indexed: false, internalType: "address", name: "winnerWallet", type: "address" },
    ],
    name: "GameFinished",
    type: "event",
  },
  { anonymous: false, inputs: [], name: "GameCancelled", type: "event" },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: "address", name: "winner", type: "address" },
      { indexed: false, internalType: "uint256", name: "amount", type: "uint256" },
      { indexed: false, internalType: "address", name: "platform", type: "address" },
      { indexed: false, internalType: "uint256", name: "fee", type: "uint256" },
    ],
    name: "PrizeDistributed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [{ indexed: true, internalType: "uint8", name: "playerIndex", type: "uint8" }],
    name: "TimeoutClaimed",
    type: "event",
  },

  // ── Write Functions ──
  {
    inputs: [],
    name: "joinGame",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "enum MarrakechGame.Direction", name: "dir", type: "uint8" }],
    name: "orientAssam",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "bytes32", name: "hash", type: "bytes32" }],
    name: "commitDice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "salt", type: "uint256" }],
    name: "revealDice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [{ internalType: "enum MarrakechGame.Direction", name: "dir", type: "uint8" }],
    name: "chooseBorderDirection",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "acknowledgeTribute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint8", name: "r1", type: "uint8" },
      { internalType: "uint8", name: "c1", type: "uint8" },
      { internalType: "uint8", name: "r2", type: "uint8" },
      { internalType: "uint8", name: "c2", type: "uint8" },
    ],
    name: "placeCarpet",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "cancelGame",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "claimTimeout",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },

  // ── View Functions ──
  {
    inputs: [],
    name: "getFullState",
    outputs: [
      { internalType: "enum MarrakechGame.GameStatus", name: "_status", type: "uint8" },
      { internalType: "enum MarrakechGame.Phase", name: "_phase", type: "uint8" },
      { internalType: "uint8", name: "_currentPlayerIndex", type: "uint8" },
      { internalType: "uint16", name: "_turnNumber", type: "uint16" },
      { internalType: "uint8", name: "_numPlayers", type: "uint8" },
      { internalType: "uint8", name: "_joinedCount", type: "uint8" },
      { internalType: "uint8", name: "_lastDiceValue", type: "uint8" },
      { internalType: "uint8", name: "_assamRow", type: "uint8" },
      { internalType: "uint8", name: "_assamCol", type: "uint8" },
      { internalType: "enum MarrakechGame.Direction", name: "_assamDir", type: "uint8" },
      { internalType: "uint8[49]", name: "_boardPlayerIds", type: "uint8[49]" },
      { internalType: "uint8[49]", name: "_boardCarpetIds", type: "uint8[49]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getGameState",
    outputs: [
      { internalType: "enum MarrakechGame.GameStatus", name: "_status", type: "uint8" },
      { internalType: "enum MarrakechGame.Phase", name: "_phase", type: "uint8" },
      { internalType: "uint8", name: "_currentPlayerIndex", type: "uint8" },
      { internalType: "uint16", name: "_turnNumber", type: "uint16" },
      { internalType: "uint8", name: "_numPlayers", type: "uint8" },
      { internalType: "uint8", name: "_joinedCount", type: "uint8" },
      { internalType: "uint8", name: "_lastDiceValue", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPlayers",
    outputs: [
      { internalType: "address[4]", name: "wallets", type: "address[4]" },
      { internalType: "uint16[4]", name: "dirhamsArr", type: "uint16[4]" },
      { internalType: "uint8[4]", name: "carpetsArr", type: "uint8[4]" },
      { internalType: "bool[4]", name: "eliminatedArr", type: "bool[4]" },
      { internalType: "bool[4]", name: "joinedArr", type: "bool[4]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getBoard",
    outputs: [
      { internalType: "uint8[49]", name: "playerIds", type: "uint8[49]" },
      { internalType: "uint8[49]", name: "carpetIds", type: "uint8[49]" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAssam",
    outputs: [
      { internalType: "uint8", name: "row", type: "uint8" },
      { internalType: "uint8", name: "col", type: "uint8" },
      { internalType: "enum MarrakechGame.Direction", name: "direction", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint8", name: "idx", type: "uint8" }],
    name: "getPlayer",
    outputs: [
      { internalType: "address", name: "wallet", type: "address" },
      { internalType: "uint16", name: "dirhams", type: "uint16" },
      { internalType: "uint8", name: "carpetsRemaining", type: "uint8" },
      { internalType: "bool", name: "eliminated", type: "bool" },
      { internalType: "bool", name: "joined", type: "bool" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "wallet", type: "address" }],
    name: "getPlayerIndex",
    outputs: [{ internalType: "int8", name: "", type: "int8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getTributeInfo",
    outputs: [
      { internalType: "uint8", name: "fromPlayer", type: "uint8" },
      { internalType: "uint8", name: "toPlayer", type: "uint8" },
      { internalType: "uint16", name: "amount", type: "uint16" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getBorderChoiceInfo",
    outputs: [
      { internalType: "uint8", name: "row", type: "uint8" },
      { internalType: "uint8", name: "col", type: "uint8" },
      { internalType: "enum MarrakechGame.Direction", name: "exitDirection", type: "uint8" },
      { internalType: "uint8", name: "remainingSteps", type: "uint8" },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "numPlayers",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "status",
    outputs: [{ internalType: "enum MarrakechGame.GameStatus", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "phase",
    outputs: [{ internalType: "enum MarrakechGame.Phase", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "stakeAmount",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "usdc",
    outputs: [{ internalType: "contract IERC20", name: "", type: "address" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lastActionBlock",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
] as const;

export const ERC20ABI = [
  {
    inputs: [
      { internalType: "address", name: "spender", type: "address" },
      { internalType: "uint256", name: "amount", type: "uint256" },
    ],
    name: "approve",
    outputs: [{ internalType: "bool", name: "", type: "bool" }],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "address", name: "owner", type: "address" },
      { internalType: "address", name: "spender", type: "address" },
    ],
    name: "allowance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "account", type: "address" }],
    name: "balanceOf",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "decimals",
    outputs: [{ internalType: "uint8", name: "", type: "uint8" }],
    stateMutability: "view",
    type: "function",
  },
] as const;
