/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MarrakechFactory } from "./MarrakechFactory";
export type { MarrakechGame } from "./MarrakechGame";
export type { MockERC20 } from "./MockERC20";
