/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface MarrakechGameInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acknowledgeTribute"
      | "assam"
      | "boardCarpetIds"
      | "boardPlayerIds"
      | "borderChoice"
      | "cancelGame"
      | "chooseBorderDirection"
      | "claimTimeout"
      | "commitDice"
      | "createdAt"
      | "currentPlayerIndex"
      | "currentTribute"
      | "diceCommit"
      | "factory"
      | "getAssam"
      | "getBoard"
      | "getBorderChoiceInfo"
      | "getFullState"
      | "getGameState"
      | "getPlayer"
      | "getPlayerIndex"
      | "getPlayers"
      | "getTributeInfo"
      | "joinGame"
      | "joinedCount"
      | "lastActionBlock"
      | "lastDiceValue"
      | "numPlayers"
      | "orientAssam"
      | "phase"
      | "placeCarpet"
      | "platformFeeBps"
      | "platformWallet"
      | "players"
      | "revealDice"
      | "stakeAmount"
      | "status"
      | "turnNumber"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssamMoved"
      | "AssamOriented"
      | "BorderChoiceRequired"
      | "BorderDirectionChosen"
      | "CarpetPlaced"
      | "DiceCommitted"
      | "DiceRevealed"
      | "GameCancelled"
      | "GameFinished"
      | "GameStarted"
      | "PlayerEliminated"
      | "PlayerJoined"
      | "PrizeDistributed"
      | "TimeoutClaimed"
      | "TributeAcknowledged"
      | "TributeCalculated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acknowledgeTribute",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "assam", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "boardCarpetIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "boardPlayerIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "borderChoice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelGame",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "chooseBorderDirection",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimTimeout",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "commitDice",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "createdAt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "currentPlayerIndex",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentTribute",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "diceCommit",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "factory", values?: undefined): string;
  encodeFunctionData(functionFragment: "getAssam", values?: undefined): string;
  encodeFunctionData(functionFragment: "getBoard", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getBorderChoiceInfo",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFullState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getGameState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayerIndex",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTributeInfo",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "joinGame", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "joinedCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastActionBlock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastDiceValue",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "numPlayers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "orientAssam",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "phase", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeCarpet",
    values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "players",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revealDice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeAmount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "status", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "turnNumber",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "acknowledgeTribute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "assam", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "boardCarpetIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "boardPlayerIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "borderChoice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chooseBorderDirection",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimTimeout",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "commitDice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createdAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentPlayerIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentTribute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "diceCommit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "factory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAssam", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getBoard", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBorderChoiceInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFullState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGameState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPlayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPlayerIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPlayers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTributeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "joinGame", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "joinedCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastActionBlock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastDiceValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "numPlayers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "orientAssam",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "phase", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "placeCarpet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "platformWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "players", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "revealDice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "status", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "turnNumber", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace AssamMovedEvent {
  export type InputTuple = [
    row: BigNumberish,
    col: BigNumberish,
    direction: BigNumberish
  ];
  export type OutputTuple = [row: bigint, col: bigint, direction: bigint];
  export interface OutputObject {
    row: bigint;
    col: bigint;
    direction: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AssamOrientedEvent {
  export type InputTuple = [playerIndex: BigNumberish, direction: BigNumberish];
  export type OutputTuple = [playerIndex: bigint, direction: bigint];
  export interface OutputObject {
    playerIndex: bigint;
    direction: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BorderChoiceRequiredEvent {
  export type InputTuple = [
    row: BigNumberish,
    col: BigNumberish,
    exitDirection: BigNumberish,
    remainingSteps: BigNumberish
  ];
  export type OutputTuple = [
    row: bigint,
    col: bigint,
    exitDirection: bigint,
    remainingSteps: bigint
  ];
  export interface OutputObject {
    row: bigint;
    col: bigint;
    exitDirection: bigint;
    remainingSteps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BorderDirectionChosenEvent {
  export type InputTuple = [playerIndex: BigNumberish, direction: BigNumberish];
  export type OutputTuple = [playerIndex: bigint, direction: bigint];
  export interface OutputObject {
    playerIndex: bigint;
    direction: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CarpetPlacedEvent {
  export type InputTuple = [
    playerIndex: BigNumberish,
    r1: BigNumberish,
    c1: BigNumberish,
    r2: BigNumberish,
    c2: BigNumberish
  ];
  export type OutputTuple = [
    playerIndex: bigint,
    r1: bigint,
    c1: bigint,
    r2: bigint,
    c2: bigint
  ];
  export interface OutputObject {
    playerIndex: bigint;
    r1: bigint;
    c1: bigint;
    r2: bigint;
    c2: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DiceCommittedEvent {
  export type InputTuple = [playerIndex: BigNumberish, commitHash: BytesLike];
  export type OutputTuple = [playerIndex: bigint, commitHash: string];
  export interface OutputObject {
    playerIndex: bigint;
    commitHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DiceRevealedEvent {
  export type InputTuple = [playerIndex: BigNumberish, value: BigNumberish];
  export type OutputTuple = [playerIndex: bigint, value: bigint];
  export interface OutputObject {
    playerIndex: bigint;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameCancelledEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameFinishedEvent {
  export type InputTuple = [
    winnerIndex: BigNumberish,
    winnerWallet: AddressLike
  ];
  export type OutputTuple = [winnerIndex: bigint, winnerWallet: string];
  export interface OutputObject {
    winnerIndex: bigint;
    winnerWallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace GameStartedEvent {
  export type InputTuple = [];
  export type OutputTuple = [];
  export interface OutputObject {}
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerEliminatedEvent {
  export type InputTuple = [playerIndex: BigNumberish];
  export type OutputTuple = [playerIndex: bigint];
  export interface OutputObject {
    playerIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PlayerJoinedEvent {
  export type InputTuple = [playerIndex: BigNumberish, wallet: AddressLike];
  export type OutputTuple = [playerIndex: bigint, wallet: string];
  export interface OutputObject {
    playerIndex: bigint;
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrizeDistributedEvent {
  export type InputTuple = [
    winner: AddressLike,
    amount: BigNumberish,
    platform: AddressLike,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    winner: string,
    amount: bigint,
    platform: string,
    fee: bigint
  ];
  export interface OutputObject {
    winner: string;
    amount: bigint;
    platform: string;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimeoutClaimedEvent {
  export type InputTuple = [playerIndex: BigNumberish];
  export type OutputTuple = [playerIndex: bigint];
  export interface OutputObject {
    playerIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TributeAcknowledgedEvent {
  export type InputTuple = [playerIndex: BigNumberish];
  export type OutputTuple = [playerIndex: bigint];
  export interface OutputObject {
    playerIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TributeCalculatedEvent {
  export type InputTuple = [
    fromPlayer: BigNumberish,
    toPlayer: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    fromPlayer: bigint,
    toPlayer: bigint,
    amount: bigint
  ];
  export interface OutputObject {
    fromPlayer: bigint;
    toPlayer: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MarrakechGame extends BaseContract {
  connect(runner?: ContractRunner | null): MarrakechGame;
  waitForDeployment(): Promise<this>;

  interface: MarrakechGameInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acknowledgeTribute: TypedContractMethod<[], [void], "nonpayable">;

  assam: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & { row: bigint; col: bigint; direction: bigint }
    ],
    "view"
  >;

  boardCarpetIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  boardPlayerIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  borderChoice: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        row: bigint;
        col: bigint;
        exitDirection: bigint;
        remainingSteps: bigint;
      }
    ],
    "view"
  >;

  cancelGame: TypedContractMethod<[], [void], "nonpayable">;

  chooseBorderDirection: TypedContractMethod<
    [dir: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimTimeout: TypedContractMethod<[], [void], "nonpayable">;

  commitDice: TypedContractMethod<[hash: BytesLike], [void], "nonpayable">;

  createdAt: TypedContractMethod<[], [bigint], "view">;

  currentPlayerIndex: TypedContractMethod<[], [bigint], "view">;

  currentTribute: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        fromPlayerIdx: bigint;
        toPlayerIdx: bigint;
        amount: bigint;
      }
    ],
    "view"
  >;

  diceCommit: TypedContractMethod<
    [],
    [[string, bigint] & { commitHash: string; commitBlock: bigint }],
    "view"
  >;

  factory: TypedContractMethod<[], [string], "view">;

  getAssam: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & { row: bigint; col: bigint; direction: bigint }
    ],
    "view"
  >;

  getBoard: TypedContractMethod<
    [],
    [[bigint[], bigint[]] & { playerIds: bigint[]; carpetIds: bigint[] }],
    "view"
  >;

  getBorderChoiceInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        row: bigint;
        col: bigint;
        exitDirection: bigint;
        remainingSteps: bigint;
      }
    ],
    "view"
  >;

  getFullState: TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint[],
        bigint[]
      ] & {
        _status: bigint;
        _phase: bigint;
        _currentPlayerIndex: bigint;
        _turnNumber: bigint;
        _numPlayers: bigint;
        _joinedCount: bigint;
        _lastDiceValue: bigint;
        _assamRow: bigint;
        _assamCol: bigint;
        _assamDir: bigint;
        _boardPlayerIds: bigint[];
        _boardCarpetIds: bigint[];
      }
    ],
    "view"
  >;

  getGameState: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        _status: bigint;
        _phase: bigint;
        _currentPlayerIndex: bigint;
        _turnNumber: bigint;
        _numPlayers: bigint;
        _joinedCount: bigint;
        _lastDiceValue: bigint;
      }
    ],
    "view"
  >;

  getPlayer: TypedContractMethod<
    [idx: BigNumberish],
    [
      [string, bigint, bigint, boolean, boolean] & {
        wallet: string;
        dirhams: bigint;
        carpetsRemaining: bigint;
        eliminated: boolean;
        joined: boolean;
      }
    ],
    "view"
  >;

  getPlayerIndex: TypedContractMethod<[wallet: AddressLike], [bigint], "view">;

  getPlayers: TypedContractMethod<
    [],
    [
      [
        [string, string, string, string],
        [bigint, bigint, bigint, bigint],
        [bigint, bigint, bigint, bigint],
        [boolean, boolean, boolean, boolean],
        [boolean, boolean, boolean, boolean]
      ] & {
        wallets: [string, string, string, string];
        dirhamsArr: [bigint, bigint, bigint, bigint];
        carpetsArr: [bigint, bigint, bigint, bigint];
        eliminatedArr: [boolean, boolean, boolean, boolean];
        joinedArr: [boolean, boolean, boolean, boolean];
      }
    ],
    "view"
  >;

  getTributeInfo: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        fromPlayer: bigint;
        toPlayer: bigint;
        amount: bigint;
      }
    ],
    "view"
  >;

  joinGame: TypedContractMethod<[], [void], "nonpayable">;

  joinedCount: TypedContractMethod<[], [bigint], "view">;

  lastActionBlock: TypedContractMethod<[], [bigint], "view">;

  lastDiceValue: TypedContractMethod<[], [bigint], "view">;

  numPlayers: TypedContractMethod<[], [bigint], "view">;

  orientAssam: TypedContractMethod<[dir: BigNumberish], [void], "nonpayable">;

  phase: TypedContractMethod<[], [bigint], "view">;

  placeCarpet: TypedContractMethod<
    [r1: BigNumberish, c1: BigNumberish, r2: BigNumberish, c2: BigNumberish],
    [void],
    "nonpayable"
  >;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  platformWallet: TypedContractMethod<[], [string], "view">;

  players: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean, boolean] & {
        wallet: string;
        dirhams: bigint;
        carpetsRemaining: bigint;
        eliminated: boolean;
        joined: boolean;
      }
    ],
    "view"
  >;

  revealDice: TypedContractMethod<[salt: BigNumberish], [void], "nonpayable">;

  stakeAmount: TypedContractMethod<[], [bigint], "view">;

  status: TypedContractMethod<[], [bigint], "view">;

  turnNumber: TypedContractMethod<[], [bigint], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acknowledgeTribute"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "assam"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & { row: bigint; col: bigint; direction: bigint }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "boardCarpetIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "boardPlayerIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "borderChoice"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        row: bigint;
        col: bigint;
        exitDirection: bigint;
        remainingSteps: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "cancelGame"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "chooseBorderDirection"
  ): TypedContractMethod<[dir: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimTimeout"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "commitDice"
  ): TypedContractMethod<[hash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createdAt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentPlayerIndex"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentTribute"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        fromPlayerIdx: bigint;
        toPlayerIdx: bigint;
        amount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "diceCommit"
  ): TypedContractMethod<
    [],
    [[string, bigint] & { commitHash: string; commitBlock: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "factory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAssam"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & { row: bigint; col: bigint; direction: bigint }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBoard"
  ): TypedContractMethod<
    [],
    [[bigint[], bigint[]] & { playerIds: bigint[]; carpetIds: bigint[] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBorderChoiceInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        row: bigint;
        col: bigint;
        exitDirection: bigint;
        remainingSteps: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFullState"
  ): TypedContractMethod<
    [],
    [
      [
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint[],
        bigint[]
      ] & {
        _status: bigint;
        _phase: bigint;
        _currentPlayerIndex: bigint;
        _turnNumber: bigint;
        _numPlayers: bigint;
        _joinedCount: bigint;
        _lastDiceValue: bigint;
        _assamRow: bigint;
        _assamCol: bigint;
        _assamDir: bigint;
        _boardPlayerIds: bigint[];
        _boardCarpetIds: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getGameState"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {
        _status: bigint;
        _phase: bigint;
        _currentPlayerIndex: bigint;
        _turnNumber: bigint;
        _numPlayers: bigint;
        _joinedCount: bigint;
        _lastDiceValue: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayer"
  ): TypedContractMethod<
    [idx: BigNumberish],
    [
      [string, bigint, bigint, boolean, boolean] & {
        wallet: string;
        dirhams: bigint;
        carpetsRemaining: bigint;
        eliminated: boolean;
        joined: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlayerIndex"
  ): TypedContractMethod<[wallet: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayers"
  ): TypedContractMethod<
    [],
    [
      [
        [string, string, string, string],
        [bigint, bigint, bigint, bigint],
        [bigint, bigint, bigint, bigint],
        [boolean, boolean, boolean, boolean],
        [boolean, boolean, boolean, boolean]
      ] & {
        wallets: [string, string, string, string];
        dirhamsArr: [bigint, bigint, bigint, bigint];
        carpetsArr: [bigint, bigint, bigint, bigint];
        eliminatedArr: [boolean, boolean, boolean, boolean];
        joinedArr: [boolean, boolean, boolean, boolean];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTributeInfo"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint] & {
        fromPlayer: bigint;
        toPlayer: bigint;
        amount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "joinGame"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "joinedCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastActionBlock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastDiceValue"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "numPlayers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "orientAssam"
  ): TypedContractMethod<[dir: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "phase"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "placeCarpet"
  ): TypedContractMethod<
    [r1: BigNumberish, c1: BigNumberish, r2: BigNumberish, c2: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "players"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, boolean, boolean] & {
        wallet: string;
        dirhams: bigint;
        carpetsRemaining: bigint;
        eliminated: boolean;
        joined: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revealDice"
  ): TypedContractMethod<[salt: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeAmount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "status"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "turnNumber"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AssamMoved"
  ): TypedContractEvent<
    AssamMovedEvent.InputTuple,
    AssamMovedEvent.OutputTuple,
    AssamMovedEvent.OutputObject
  >;
  getEvent(
    key: "AssamOriented"
  ): TypedContractEvent<
    AssamOrientedEvent.InputTuple,
    AssamOrientedEvent.OutputTuple,
    AssamOrientedEvent.OutputObject
  >;
  getEvent(
    key: "BorderChoiceRequired"
  ): TypedContractEvent<
    BorderChoiceRequiredEvent.InputTuple,
    BorderChoiceRequiredEvent.OutputTuple,
    BorderChoiceRequiredEvent.OutputObject
  >;
  getEvent(
    key: "BorderDirectionChosen"
  ): TypedContractEvent<
    BorderDirectionChosenEvent.InputTuple,
    BorderDirectionChosenEvent.OutputTuple,
    BorderDirectionChosenEvent.OutputObject
  >;
  getEvent(
    key: "CarpetPlaced"
  ): TypedContractEvent<
    CarpetPlacedEvent.InputTuple,
    CarpetPlacedEvent.OutputTuple,
    CarpetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "DiceCommitted"
  ): TypedContractEvent<
    DiceCommittedEvent.InputTuple,
    DiceCommittedEvent.OutputTuple,
    DiceCommittedEvent.OutputObject
  >;
  getEvent(
    key: "DiceRevealed"
  ): TypedContractEvent<
    DiceRevealedEvent.InputTuple,
    DiceRevealedEvent.OutputTuple,
    DiceRevealedEvent.OutputObject
  >;
  getEvent(
    key: "GameCancelled"
  ): TypedContractEvent<
    GameCancelledEvent.InputTuple,
    GameCancelledEvent.OutputTuple,
    GameCancelledEvent.OutputObject
  >;
  getEvent(
    key: "GameFinished"
  ): TypedContractEvent<
    GameFinishedEvent.InputTuple,
    GameFinishedEvent.OutputTuple,
    GameFinishedEvent.OutputObject
  >;
  getEvent(
    key: "GameStarted"
  ): TypedContractEvent<
    GameStartedEvent.InputTuple,
    GameStartedEvent.OutputTuple,
    GameStartedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerEliminated"
  ): TypedContractEvent<
    PlayerEliminatedEvent.InputTuple,
    PlayerEliminatedEvent.OutputTuple,
    PlayerEliminatedEvent.OutputObject
  >;
  getEvent(
    key: "PlayerJoined"
  ): TypedContractEvent<
    PlayerJoinedEvent.InputTuple,
    PlayerJoinedEvent.OutputTuple,
    PlayerJoinedEvent.OutputObject
  >;
  getEvent(
    key: "PrizeDistributed"
  ): TypedContractEvent<
    PrizeDistributedEvent.InputTuple,
    PrizeDistributedEvent.OutputTuple,
    PrizeDistributedEvent.OutputObject
  >;
  getEvent(
    key: "TimeoutClaimed"
  ): TypedContractEvent<
    TimeoutClaimedEvent.InputTuple,
    TimeoutClaimedEvent.OutputTuple,
    TimeoutClaimedEvent.OutputObject
  >;
  getEvent(
    key: "TributeAcknowledged"
  ): TypedContractEvent<
    TributeAcknowledgedEvent.InputTuple,
    TributeAcknowledgedEvent.OutputTuple,
    TributeAcknowledgedEvent.OutputObject
  >;
  getEvent(
    key: "TributeCalculated"
  ): TypedContractEvent<
    TributeCalculatedEvent.InputTuple,
    TributeCalculatedEvent.OutputTuple,
    TributeCalculatedEvent.OutputObject
  >;

  filters: {
    "AssamMoved(uint8,uint8,uint8)": TypedContractEvent<
      AssamMovedEvent.InputTuple,
      AssamMovedEvent.OutputTuple,
      AssamMovedEvent.OutputObject
    >;
    AssamMoved: TypedContractEvent<
      AssamMovedEvent.InputTuple,
      AssamMovedEvent.OutputTuple,
      AssamMovedEvent.OutputObject
    >;

    "AssamOriented(uint8,uint8)": TypedContractEvent<
      AssamOrientedEvent.InputTuple,
      AssamOrientedEvent.OutputTuple,
      AssamOrientedEvent.OutputObject
    >;
    AssamOriented: TypedContractEvent<
      AssamOrientedEvent.InputTuple,
      AssamOrientedEvent.OutputTuple,
      AssamOrientedEvent.OutputObject
    >;

    "BorderChoiceRequired(uint8,uint8,uint8,uint8)": TypedContractEvent<
      BorderChoiceRequiredEvent.InputTuple,
      BorderChoiceRequiredEvent.OutputTuple,
      BorderChoiceRequiredEvent.OutputObject
    >;
    BorderChoiceRequired: TypedContractEvent<
      BorderChoiceRequiredEvent.InputTuple,
      BorderChoiceRequiredEvent.OutputTuple,
      BorderChoiceRequiredEvent.OutputObject
    >;

    "BorderDirectionChosen(uint8,uint8)": TypedContractEvent<
      BorderDirectionChosenEvent.InputTuple,
      BorderDirectionChosenEvent.OutputTuple,
      BorderDirectionChosenEvent.OutputObject
    >;
    BorderDirectionChosen: TypedContractEvent<
      BorderDirectionChosenEvent.InputTuple,
      BorderDirectionChosenEvent.OutputTuple,
      BorderDirectionChosenEvent.OutputObject
    >;

    "CarpetPlaced(uint8,uint8,uint8,uint8,uint8)": TypedContractEvent<
      CarpetPlacedEvent.InputTuple,
      CarpetPlacedEvent.OutputTuple,
      CarpetPlacedEvent.OutputObject
    >;
    CarpetPlaced: TypedContractEvent<
      CarpetPlacedEvent.InputTuple,
      CarpetPlacedEvent.OutputTuple,
      CarpetPlacedEvent.OutputObject
    >;

    "DiceCommitted(uint8,bytes32)": TypedContractEvent<
      DiceCommittedEvent.InputTuple,
      DiceCommittedEvent.OutputTuple,
      DiceCommittedEvent.OutputObject
    >;
    DiceCommitted: TypedContractEvent<
      DiceCommittedEvent.InputTuple,
      DiceCommittedEvent.OutputTuple,
      DiceCommittedEvent.OutputObject
    >;

    "DiceRevealed(uint8,uint8)": TypedContractEvent<
      DiceRevealedEvent.InputTuple,
      DiceRevealedEvent.OutputTuple,
      DiceRevealedEvent.OutputObject
    >;
    DiceRevealed: TypedContractEvent<
      DiceRevealedEvent.InputTuple,
      DiceRevealedEvent.OutputTuple,
      DiceRevealedEvent.OutputObject
    >;

    "GameCancelled()": TypedContractEvent<
      GameCancelledEvent.InputTuple,
      GameCancelledEvent.OutputTuple,
      GameCancelledEvent.OutputObject
    >;
    GameCancelled: TypedContractEvent<
      GameCancelledEvent.InputTuple,
      GameCancelledEvent.OutputTuple,
      GameCancelledEvent.OutputObject
    >;

    "GameFinished(uint8,address)": TypedContractEvent<
      GameFinishedEvent.InputTuple,
      GameFinishedEvent.OutputTuple,
      GameFinishedEvent.OutputObject
    >;
    GameFinished: TypedContractEvent<
      GameFinishedEvent.InputTuple,
      GameFinishedEvent.OutputTuple,
      GameFinishedEvent.OutputObject
    >;

    "GameStarted()": TypedContractEvent<
      GameStartedEvent.InputTuple,
      GameStartedEvent.OutputTuple,
      GameStartedEvent.OutputObject
    >;
    GameStarted: TypedContractEvent<
      GameStartedEvent.InputTuple,
      GameStartedEvent.OutputTuple,
      GameStartedEvent.OutputObject
    >;

    "PlayerEliminated(uint8)": TypedContractEvent<
      PlayerEliminatedEvent.InputTuple,
      PlayerEliminatedEvent.OutputTuple,
      PlayerEliminatedEvent.OutputObject
    >;
    PlayerEliminated: TypedContractEvent<
      PlayerEliminatedEvent.InputTuple,
      PlayerEliminatedEvent.OutputTuple,
      PlayerEliminatedEvent.OutputObject
    >;

    "PlayerJoined(uint8,address)": TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;
    PlayerJoined: TypedContractEvent<
      PlayerJoinedEvent.InputTuple,
      PlayerJoinedEvent.OutputTuple,
      PlayerJoinedEvent.OutputObject
    >;

    "PrizeDistributed(address,uint256,address,uint256)": TypedContractEvent<
      PrizeDistributedEvent.InputTuple,
      PrizeDistributedEvent.OutputTuple,
      PrizeDistributedEvent.OutputObject
    >;
    PrizeDistributed: TypedContractEvent<
      PrizeDistributedEvent.InputTuple,
      PrizeDistributedEvent.OutputTuple,
      PrizeDistributedEvent.OutputObject
    >;

    "TimeoutClaimed(uint8)": TypedContractEvent<
      TimeoutClaimedEvent.InputTuple,
      TimeoutClaimedEvent.OutputTuple,
      TimeoutClaimedEvent.OutputObject
    >;
    TimeoutClaimed: TypedContractEvent<
      TimeoutClaimedEvent.InputTuple,
      TimeoutClaimedEvent.OutputTuple,
      TimeoutClaimedEvent.OutputObject
    >;

    "TributeAcknowledged(uint8)": TypedContractEvent<
      TributeAcknowledgedEvent.InputTuple,
      TributeAcknowledgedEvent.OutputTuple,
      TributeAcknowledgedEvent.OutputObject
    >;
    TributeAcknowledged: TypedContractEvent<
      TributeAcknowledgedEvent.InputTuple,
      TributeAcknowledgedEvent.OutputTuple,
      TributeAcknowledgedEvent.OutputObject
    >;

    "TributeCalculated(uint8,uint8,uint16)": TypedContractEvent<
      TributeCalculatedEvent.InputTuple,
      TributeCalculatedEvent.OutputTuple,
      TributeCalculatedEvent.OutputObject
    >;
    TributeCalculated: TypedContractEvent<
      TributeCalculatedEvent.InputTuple,
      TributeCalculatedEvent.OutputTuple,
      TributeCalculatedEvent.OutputObject
    >;
  };
}
