/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MarrakechFactory__factory } from "./MarrakechFactory__factory";
export { MarrakechGame__factory } from "./MarrakechGame__factory";
export { MockERC20__factory } from "./MockERC20__factory";
